baseURL = 'http://odessar.github.io/'
theme        = "hello-friend-ng"
paginate     = 10
languageCode = 'en-us'
title = 'Hello, I am Odessa'


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
    # Enable to show reading time in minutes for posts
  showReadingTime = true


  # Subtitle for home
  homeSubtitle = "Software Engineer and Data Addict"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Software Engineer and Data Addict"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello, I am Odessa"
    subtitle = "Software Engineer and Data Addict"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = " % cd /homepage/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

[[params.social]]
  name = "github"
  url = "https://github.com/OdessaR"
[[params.social]]
  name = "email"
  url = "mailto:yaping.ren@hotmail.com"
[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/yaping-ren/"
  

  # And you can even create generic menu
  [[menu.main]]
    identifier = "post"
    name       = "Posts"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"